# Generated by Django 4.1.1 on 2023-01-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=75)),
                ("grs_lintang", models.FloatField(null=True)),
                ("grs_bujur", models.FloatField(null=True)),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Peralatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_Alat", models.CharField(max_length=75)),
                ("harga", models.CharField(max_length=50)),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("deskripsi", models.CharField(max_length=650)),
            ],
        ),
    ]
